name: Merge Request

on:
  pull_request:
    branches: [ "main" ]
    
env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry

jobs:
  windows-ui-build:
    runs-on: windows-2022
    name: Windows UI Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          include-prerelease: true

      - name: Restore Dependencies
        run: dotnet restore src/Edsm.Sdk.sln        
        
      - name: Run Tests
        run: dotnet test .\src\Edsm.Sdk.sln